const gifs = [
  "https://imgur.com/GCa9Bna.gif",
  "https://imgur.com/mKemAzO.gif",
  "https://imgur.com/EzyE4Dh.gif",
  "https://imgur.com/fD6Epke.gif",
  "https://imgur.com/DIBcg0e.gif",
  "https://imgur.com/GU9rZ4A.gif",
  "https://imgur.com/cPYI0S5.gif",
  "https://imgur.com/BNyqoqO.gif",
  "https://imgur.com/J9DKjoy.gif",
  "https://imgur.com/z2Wiop2.gif",
  "https://imgur.com/2yfkgba.gif",
  "https://imgur.com/VRkr6hz.gif",
  "https://imgur.com/T46r9vt.gif",
  "https://imgur.com/tRYbYkl.gif",
  "https://imgur.com/qS1icFv.gif",
  "https://imgur.com/w2hzcy3.gif",
  "https://imgur.com/gd6fgB1.gif",
  "https://imgur.com/Tmpgp9r.gif",
  "https://imgur.com/dhBPYih.gif",
  "https://imgur.com/hGBxAbr.gif",
  "https://imgur.com/lMjq9Gy.gif",
  "https://imgur.com/qtdLbLk.gif",
  "https://imgur.com/RVfny4H.gif",
  "https://imgur.com/5qOZhpX.gif",
  "https://imgur.com/YhztOeH.gif",
  "https://imgur.com/97xxt84.gif",
  "https://imgur.com/hErCSYE.gif",
  "https://imgur.com/db8PHV0.gif",
  "https://imgur.com/7QFD775.gif",
  "https://imgur.com/mx62NsZ.gif",
  "https://imgur.com/7V9yXJ5.gif",
  "https://imgur.com/gKfbvts.gif",
  "https://imgur.com/8jCS5OV.gif",
  "https://imgur.com/RNNANJY.gif",
  "https://imgur.com/J0PjKp9.gif",
  "https://imgur.com/bdxskhm.gif",
  "https://imgur.com/aJDmSJY.gif",
  "https://imgur.com/Mn5x3Sw.gif",
  "https://imgur.com/T2jJteS.gif",
  "https://imgur.com/vPDBeW1.gif",
  "https://imgur.com/DVYG7LQ.gif",
  "https://imgur.com/Lsd6L46.gif",
  "https://imgur.com/wbeqO5Q.gif",
  "https://imgur.com/w5fce1D.gif",
  "https://imgur.com/XBpPtRO.gif",
];

export default {
  name: "hug",
  main: function (user, author) {
    const responses = [
      `${user} was hugged by ${author}, very wholesome!`,
      `${author} hugs ${user}!`,
      `${author} is hugging ${user}!`,
      `${user} and ${author} are hugging!`,
    ];
    return [responses, gifs];
  },
};
