const gifs = [
  "https://imgur.com/symESWL.gif",
  "https://imgur.com/lZlBz92.gif",
  "https://imgur.com/aVcWoi7.gif",
  "https://imgur.com/sxqfRxF.gif",
  "https://imgur.com/mwSQrCb.gif",
  "https://imgur.com/RIZXcWm.gif",
  "https://imgur.com/fI63MC2.gif",
  "https://imgur.com/9gULMTt.gif",
  "https://imgur.com/Yp0UxR7.gif",
  "https://imgur.com/g8XbCmY.gif",
  "https://imgur.com/kUkjrY1.gif",
  "https://imgur.com/oBhNqpl.gif",
  "https://imgur.com/n2FCf6v.gif",
  "https://imgur.com/e2MYtTN.gif",
  "https://imgur.com/aBCbHuw.gif",
  "https://imgur.com/pSQ9k5I.gif",
  "https://imgur.com/4NmSHHl.gif",
  "https://imgur.com/EnaztzD.gif",
  "https://imgur.com/U1F8C6l.gif",
  "https://imgur.com/jM4OQ9j.gif",
  "https://imgur.com/jdhIfcE.gif",
  "https://imgur.com/mrJsZwU.gif",
  "https://imgur.com/cRU6LNp.gif",
  "https://imgur.com/V1HrzoA.gif",
  "https://imgur.com/6nyHADT.gif",
  "https://imgur.com/0aF1ksw.gif",
  "https://imgur.com/fmj38F0.gif",
  "https://imgur.com/YLMI3bF.gif",
  "https://imgur.com/pmSZcEV.gif",
  "https://imgur.com/OwvBbnd.gif",
  "https://imgur.com/B2ywrRI.gif",
  "https://imgur.com/Lcjmcdf.gif",
  "https://imgur.com/X6Ki1uF.gif",
  "https://imgur.com/IiFHT5o.gif",
  "https://imgur.com/IwOj9K1.gif",
  "https://imgur.com/34QZr7f.gif",
  "https://imgur.com/e2ioiXY.gif",
  "https://imgur.com/FOWkE2R.gif",
  "https://imgur.com/2EHMss1.gif",
  "https://imgur.com/5flDkA1.gif",
  "https://imgur.com/oqErdx1.gif",
  "https://imgur.com/wNNjuIM.gif",
  "https://imgur.com/RaaGS1Q.gif",
  "https://imgur.com/2d7vh2d.gif",
  "https://imgur.com/ry2dTj6.gif",
];

export default {
  name: "pat",
  main: function (user, author) {
    const responses = [
      `${user} is being patted by ${author}!`,
      `${author} patted ${user}!`,
      `${author} is patting ${user}!`,
      `${author} pats ${user}!`,
    ];
    return [responses, gifs];
  },
};
